name: Daily Chess Puzzle Upload

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    env:
      FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Stockfish
        run: sudo apt-get update && sudo apt-get install -y stockfish

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install firebase-admin requests python-chess stockfish

      - name: Run uploader
        run: python upload_puzzle.py
